import type { Metadata } from "next";
import "./globals.css";
import Footer from "./Component/Shared/Footer/Footer1";
import Faq from "./Component/Shared/Faq/Faq1";
import Header from "./Component/Shared/Header/Header";

export const metadata: Metadata = {
  title: "Global Access",
  description: "Generated by Grow web services",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Faq />
        <Footer />
      </body>
    </html>
  );
}
